#!/usr/bin/env bash
# install and setup haproxy on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 54853-web-01 54.162.240.228 check
    server 54853-web-02 100.26.172.251 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
